groups:
- name: all
  jobs:
  - build-broker
  - build-tile
  - claim-pcf
  - deploy-tile
  - remove-tile
  - release-pcf
- name: manual
  jobs:
  - manual-release-pcf

resources:
- name: version
  type: semver
  source:
    bucket: apigee-cf-service-broker-tile
    key: current-version
    access_key_id: {{aws-key-id}}
    secret_access_key: {{aws-key}}
    initial-version: 2.1.0

- name: tile-repo
  type: git
  source:
    uri: https://github.com/apigee/pivotal-cf-apigee.git
    branch: master

- name: broker-zip
  type: s3
  source:
    access_key_id: {{aws-key-id}}
    bucket: apigee-cf-service-broker-tile
    regexp: .*-(?P<version>.*)\.zip
    secret_access_key: {{aws-key}}

- name: broker-tile
  type: s3
  source:
    access_key_id: {{aws-key-id}}
    bucket: apigee-cf-service-broker-tile
    regexp: .*-(?P<version>.*)\.pivotal
    secret_access_key: {{aws-key}}

- name: tile-history
  type: s3
  source:
    access_key_id: {{aws-key-id}}
    bucket: apigee-cf-service-broker-tile
    regexp: tile\-history-(?P<version>.*)\.yml
    secret_access_key: {{aws-key}}

- name: pcf-environment
  type: pool
  source:
    branch: master
    pool: pcf
    private_key: {{github-pool-private-key}}
    uri: git@github.com:cf-platform-eng/pipeline-resource-pool-v2

jobs:
- name: build-broker
  serial_groups: [version]
  plan:
  - get: tile-repo
    trigger: true
  - get: version
    params: {bump: patch}
  - task: build-broker
    file: tile-repo/apigee-cf-service-broker/ci/build-broker/task.yml
  - put: broker-zip
    params: {file: broker-zip/*.zip}
  - put: version
    params: {file: version/number}

- name: build-tile
  serial_groups: [version]
  plan:
  - aggregate:
    - get: tile-repo
    - get: broker-zip
      trigger: true
      passed:
        - build-broker
    - get: version
    - get: tile-history
  - task: build-tile
    file: tile-repo/apigee-cf-service-broker/ci/build-tile/task.yml
  - put: tile-history
    params: {file: tile-history-new/*.yml}
  - put: broker-tile
    params:
      file: broker-tile/*.pivotal

- name: claim-pcf
  serial_groups: [version]
  plan:
  - aggregate:
    - get: broker-tile
      trigger: true
      passed:
      - build-tile
  - put: pcf-environment
    params:
      acquire: true

- name: deploy-tile
  plan:
  - aggregate:
    - get: broker-tile
      passed:
      - claim-pcf
      trigger: true
    - get: pcf-environment
      passed:
      - claim-pcf
    - get: tile-repo
    - get: version
  - task: deploy-tile
    file: tile-repo/apigee-cf-service-broker/ci/deploy-tile/task.yml
    on_failure:
      aggregate:
      - put: pcf-environment
        params:
          release: pcf-environment

- name: remove-tile
  plan:
  - aggregate:
    - get: tile-repo
    - get: broker-tile
    - get: pcf-environment
      passed:
        - deploy-tile
      trigger: true
  - task: remove-tile
    file: tile-repo/apigee-cf-service-broker/ci/remove-tile/task.yml
    on_failure:
      aggregate:
      - put: pcf-environment
        params:
          release: pcf-environment"

- name: release-pcf
  plan:
  - get: pcf-environment
    passed:
    - remove-tile
    trigger: true
  - put: pcf-environment
    params:
      release: pcf-environment

- name: manual-release-pcf
  plan:
  - get: pcf-environment
    passed:
    - claim-pcf
  - put: pcf-environment
    params:
      release: pcf-environment
